{% set name = "trame-xterm" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/trame-xterm-{{ version }}.tar.gz
  sha256: 208ca977325e7c7b77fe5e1a42d0f54531d2f2d5ecf1e05c666ddf3269e5e41d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - trame-client
    - termcolor

test:
  imports:
    - trame
    - trame_xterm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Kitware/trame-xterm
  summary: Trame widget to expose xterm.js
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jourdain
    - psavery
